=== tiniacoleyba/uned-web-programming/dir_xml/anunciantes.dtd
<!ELEMENT anunciantes (anunciante+)>
<!ELEMENT anunciante (idanunciante,empresa,cif,correo+,anuncios)>
<!ELEMENT idanunciante (#PCDATA)>
<!ELEMENT empresa (#PCDATA)>
<!ELEMENT cif (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT anuncios (total,activos,anuncio+)>
<!ELEMENT total (#PCDATA)>
<!ELEMENT activos (#PCDATA)>
<!ELEMENT anuncio (posicion,modo,fecha,(texto|imagen))>
<!ELEMENT posicion EMPTY>
<!ELEMENT modo EMPTY>
<!ELEMENT fecha (ano,mes,dia)>
<!ELEMENT ano (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT texto (mensaje)>
<!ELEMENT mensaje (#PCDATA)>
<!ELEMENT imagen (fuente,tamano)>
<!ELEMENT fuente (#PCDATA)>
<!ELEMENT tamano EMPTY>

<!ATTLIST anunciante aid ID #REQUIRED>
<!ATTLIST anuncio activo (0|1) #REQUIRED idan ID #REQUIRED>
<!ATTLIST posicion tipo (laterales|cabecera|incrustado) #REQUIRED>
<!ATTLIST modo tipo (simple|pop-up) #REQUIRED>
<!ATTLIST tamano tipo (peq|mediano|grande) #REQUIRED>

=== tiniacoleyba/uned-web-programming/dir_xml/anunciantes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE anunciantes SYSTEM "anunciantes.dtd">
<anunciantes>
    <anunciante aid="x002B">
        <idanunciante>mooglex002b</idanunciante>
        <empresa>Moogle</empresa>
        <cif>123456789X</cif>
        <correo>mooglemarketing@moogle.com</correo>
        <correo>servicio@moogle.com</correo>
        <anuncios>
            <total>2</total>
            <activos>1</activos>
            <anuncio activo="1" idan="x021">
                <posicion tipo="laterales"/>
                <modo tipo="simple"/>
                <fecha>
                    <ano>2020</ano>
                    <mes>02</mes>
                    <dia>04</dia>
                </fecha>
                <texto>
                    <mensaje>Tenga toda su informaci√≥n en venta a terceros! Oferta
                        ahora solo por 899&nbsp;&euro; antes 1321&nbsp;&euro; con
                        el nuevo trollsphone99.
                    </mensaje>
                </texto>
            </anuncio>
            <anuncio activo="0" idan="x004">
                <posicion tipo="cabecera"/>
                <modo tipo="pop-up"/>
                <fecha>
                    <ano>2019</ano>
                    <mes>07</mes>
                    <dia>27</dia>
                </fecha>
                <imagen>
                    <fuente>moogle-terceros.svg</fuente>
                    <tamano tipo="mediano"/>
                </imagen>
            </anuncio>
        </anuncios>
    </anunciante>
    <anunciante aid="x0009">
        <idanunciante>bastidonx0009</idanunciante>
        <empresa>Bastidon</empresa>
        <cif>323456789A</cif>
        <correo>marketing@bastidon.net</correo>
        <anuncios>
            <total>1</total>
            <activos>1</activos>
            <anuncio activo="1" idan="x0FF">
                <posicion tipo="incrustado"/>
                <modo tipo="simple"/>
                <fecha>
                    <ano>2020</ano>
                    <mes>03</mes>
                    <dia>05</dia>
                </fecha>
                <imagen>
                    <fuente>batidon-oferta.jpeg</fuente>
                    <tamano tipo="peq"/>
                </imagen>
            </anuncio>
        </anuncios>
    </anunciante>
</anunciantes>
