=== tiniacoleyba/uned-web-programming/dir_xml/usuarios.dtd
<!ELEMENT usuarios (usuario+)>
<!ELEMENT usuario (idusuario,nombre,apellido,edad?,sexo?,telefono*,correo,
clave,recuperacion,uso)>
<!ELEMENT idusuario (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT sexo EMPTY>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT clave (#PCDATA)>
<!ELEMENT recuperacion (pregunta,twofa)>
<!ELEMENT pregunta (#PCDATA)>
<!ELEMENT twofa EMPTY>
<!ELEMENT uso (subscripcion,accesos,registro)>
<!ELEMENT subscripcion EMPTY>
<!ELEMENT accesos (#PCDATA)>
<!ELEMENT registro (ano,mes,dia)>
<!ELEMENT ano (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT dia (#PCDATA)>

<!ATTLIST usuario uid ID #REQUIRED>
<!ATTLIST sexo s (f|m) #REQUIRED>
<!ATTLIST telefono tipo (movil|fijo|nulo) #REQUIRED>
<!ATTLIST correo tipo (personal|laboral) "personal">
<!ATTLIST pregunta tipo (animal|deporte|hermano|ciudad) #REQUIRED>
<!ATTLIST twofa habilitado (0|1) "0">
<!ATTLIST subscripcion tipo (ninguna|normal|premiun) #REQUIRED>

=== tiniacoleyba/uned-web-programming/dir_xml/usuarios.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE usuarios SYSTEM "usuarios.dtd">
<usuarios>
    <usuario uid="x000A">
        <idusuario>josemhg</idusuario>
        <nombre>José María</nombre>
        <apellido>Hernández González</apellido>
        <edad>43</edad>
        <sexo s="m"/>
        <telefono tipo="movil">666123999</telefono>
        <correo tipo="personal">josemhg@gmail.com</correo>
        <clave>josemgH19770911;</clave>
        <recuperacion>
            <pregunta tipo="deporte">salto-base</pregunta>
            <twofa habilitado="1"/>
        </recuperacion>
        <uso>
            <subscripcion tipo="premiun"/>
            <accesos>731</accesos>
            <registro>
                <ano>2016</ano>
                <mes>7</mes>
                <dia>30</dia>
            </registro>
        </uso>
    </usuario>
    <usuario uid="x001F">
        <idusuario>victoriacg</idusuario>
        <nombre>Victoria</nombre>
        <apellido>Contrera García</apellido>
        <edad></edad>
        <sexo s="f"/>
        <telefono tipo="nulo"></telefono>
        <correo tipo="personal">victoriacg@yandex.com</correo>
        <clave>vIctoriacg44;</clave>
        <recuperacion>
            <pregunta tipo="animal">Koala</pregunta>
            <twofa habilitado="0"/>
        </recuperacion>
        <uso>
            <subscripcion tipo="normal"/>
            <accesos>33</accesos>
            <registro>
                <ano>2019</ano>
                <mes>11</mes>
                <dia>17</dia>
            </registro>
        </uso>
    </usuario>
</usuarios>
